version: "3.9"  # or the version you prefer

services:
  kitchen-table:
    build:
      context: .
      dockerfile: Dockerfile  # Ensure this matches your actual Dockerfile name
    ports:
      - "443:8080"  # Maps port 443 on the host to 8080 on the container
      - "80:8080"
    env_file:
      - .env        # Points to your .env file for environment variables
    container_name: kitchen_table
    restart: always # Ensures the container restarts automatically if it stops