# Generated by Django 5.1.4 on 2025-01-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postentry',
            name='status',
            field=models.CharField(choices=[('Live', 'Live'), ('Draft', 'Draft')], default='Live', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='secretsignupcode',
            name='code',
            field=models.CharField(max_length=300),
        ),
    ]
