# Generated by Django 5.1.4 on 2025-01-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_postentry_last_updated_alter_postentry_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='local_timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
