# Generated by Django 5.1.4 on 2025-01-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_imageupload_options_imageupload_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='date_taken',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
