# Generated by Django 5.1.4 on 2025-01-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_imageupload_date_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='date_taken',
            field=models.DateField(blank=True, null=True),
        ),
    ]
