# Generated by Django 5.1.4 on 2025-01-17 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_imageupload_date_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='date_taken',
            field=models.DateField(default=datetime.datetime(2025, 1, 17, 15, 20, 55, 112080, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
